name: Deploy Pukara Blog Theme

on:
  push:
    branches:
      - main
    paths:
      - "themes/blog-pukaradev/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy theme via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: fusm4.siteground.biz
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: themes/blog-pukaradev
          server-dir: /wp-content/themes/blogpukara
